### ISSUE TITLE
The scale of the color bar

### ISSUE THREAD

**Issue by leeeru1987** [AdityaRoy-1996/Projected-Bands-in-Quantum-Espresso#8]
Dear AdityaRoy
I have used your python code to plot the spin projection of the band structure, but the color bar doesn't have any scale, would you please fix it.
![微信图片_20241217162339](https://github.com/user-attachments/assets/c944aa7b-f13c-4a07-ae32-bf603b8e3e12)

**Comment by AdityaRoy-1996** [comment]
Dear @leeeru1987, thanks for contacting regarding the issue you faced. Currently the projections are in 4th place of decimal and labeling them are a tedious task while plotting. I encourage you to label the color bar as normalization from 0 (lower) to 1(upper).

**Comment by leeeru1987** [comment]
I got it, I can label it by hand
